version: '3.8'

services:
  nginx:
    image: nginx:latest
    container_name: softmarkbackend-nginx
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - nodejs-app
    networks:
      - softmarkbackend_network

  nodejs-app:
    build: .
    container_name: softmarkbackend-nodejs-app
    environment:
      - POSTGRES_HOST=34.235.156.8
      - DB_PORT=5433
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
      - REDIS_HOST=34.235.156.8
      - REDIS_PORT=6379
      - EMAIL=fa21bscs0017@maju.edu.pk
      - "EMAIL_PASS=eoeb amae fgaw adeu"
      - ADMIN_EMAIL=info@softmarksolutions.com
      - STRIPE_SECRET_KEY=sk_test_51PZYVZ2LenqTzirVBVYT4B83dZvQ79Lb4FKiODaO60gLHWMdJF2IKbmRo3z9cAYLTy8SSdMUPJnwtdUVWi5mnp9l00cFOM2uMq
      - PORT=4000
    ports:
      - "4000:4000"
    depends_on:
      - pgsql
      - redis
    networks:
      - softmarkbackend_network
    entrypoint: ["./wait-for-it.sh", "pgsql:5433", "--", "./wait-for-it.sh", "redis:6379", "--", "npm", "start"]

  pgsql:
    image: postgres:12.19
    container_name: softmarkbackend-pgsql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5433:5432"
    volumes:
      - pgsql-data:/var/lib/postgresql/data
    networks:
      - softmarkbackend_network

  redis:
    image: redis:7.2.5
    container_name: softmarkbackend-redis
    ports:
      - "6379:6379"
    networks:
      - softmarkbackend_network

  adminer:
    image: adminer
    container_name: softmarkbackend-adminer
    environment:
      ADMINER_DEFAULT_SERVER: pgsql
    ports:
      - "8080:8080"
    networks:
      - softmarkbackend_network

networks:
  softmarkbackend_network:
    driver: bridge

volumes:
  pgsql-data:
