version: "3"

services:
  nodejs-app:
    build: .
    container_name: softmarkbackend-nodejs-app
    environment:
      - POSTGRES_HOST=pgsql
      - DB_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - EMAIL=fa21bscs0017@maju.edu.pk
      - EMAIL_PASS=eoeb amae fgaw adeu
      - ADMIN_EMAIL=info@softmarksolutions.com
    ports:
      - "4000:4000"
    depends_on:
      - pgsql
      - redis
    networks:
      - softmarkbackend_network

  pgsql:
    image: postgres:12.19
    container_name: softmarkbackend-pgsql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5433:5432"
    volumes:
      - pgsql-data:/var/lib/postgresql/data
    networks:
      - softmarkbackend_network

  redis:
    image: redis:7.2.5
    container_name: softmarkbackend-redis
    ports:
      - "6379:6379"
    networks:
      - softmarkbackend_network

  adminer:
    image: adminer
    container_name: softmarkbackend-adminer
    environment:
      ADMINER_DEFAULT_SERVER: pgsql
    ports:
      - "8080:8080"
    networks:
      - softmarkbackend_network

networks:
  softmarkbackend_network:
    driver: bridge

volumes:
  pgsql-data:
