version: '3.9'

services:
  pgsql:
    image: postgres:14.12
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - backend

  redis:
    image: redis:7.2.5
    ports:
      - "6379:6379"
    networks:
      - backend

  nodejs-app:
    image: softmarkbackend-nodejs-app
    build: .
    command: sh -c "./wait-for-it.sh pgsql:5432 -- ./wait-for-it.sh redis:6379 -- npm start"
    volumes:
      - .:/src/app
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
      POSTGRES_HOST: pgsql
      DB_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      REDIS_HOST: redis
      REDIS_PORT: 6379
      Email: fa21bscs0017@maju.edu.pk
      Email_PASS: cxan vcqf dikr aqob
      ADMIN_EMAIL: fa21bscs0017@maju.edu.pk
    depends_on:
      - pgsql
      - redis
    networks:
      - backend

  adminer:
    image: adminer
    restart: always
    ports:
      - "8081:8080"
    networks:
      - backend

volumes:
  db:

networks:
  backend:
    driver: bridge
