version: '4'

services:
  nodejs-app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - pgsql
      - redis
    environment:
      NODE_ENV: development
      DB_HOST: pgsql
      DB_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      REDIS_HOST: redis
      REDIS_PORT: 6379
    volumes:
      - .:/usr/src/app
    command: sh -c "npm install && npm rebuild bcrypt --build-from-source && node server.js"

  pgsql:
    image: postgres:14.12 
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7.2.5
    ports:
      - "6379:6379"
      
  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080

volumes:
  pgdata:
