version: '3.7'

services:
  pgsql:
    image: postgres:14.7
    volumes:
      - ./db:/var/lib/postgresql/data
      - ./postgres-initdb.sh:/docker-entrypoint-initdb.d/initdb.sh
    ports:
      - "5433:5432"
    networks:
      - dev-network
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres

  redis:
    image: redis
    ports:
      - "6380:6379"
    networks:
      - dev-network

  adminer:
    image: adminer
    ports:
      - "8080:8080"
    networks:
      - dev-network

networks:
  dev-network:
    driver: bridge
